---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
      config-file: molecule/resources/yaml-lint.yml
platforms:
  - name: debian
    image: debian:stretch
    dockerfile: ../resources/playbooks/Dockerfile.j2
    privileged: True
    # cap_add:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # command: "/bin/systemd"
  # - name: centos
  #   image: centos:7
  #   dockerfile: ../resources/playbooks/Dockerfile.j2
  #   privileged: True
    # cap_add:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../resources/roles/
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: svn
  test_sequence:
    # - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../resources/tests/*
  env:
    # remove the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
    enabled: False
