---
- name: ANSISTRANO | Gather releases
  find:
    paths: "{{ ansistrano_releases_path }}"
    file_type: directory
    recurse: false
  register: ansistrano_releases
  when: ansistrano_keep_releases | int > 0

- name: ANSISTRANO | Clean up releases
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ (ansistrano_releases.files | sort(attribute='mtime', reverse=true))[ansistrano_keep_releases | int:] }}"
  when: ansistrano_keep_releases | int > 0
