---
# Update using synchronize strategy
- name: Ensure shared copy for rsync improvement exists (in rsync case)
  file: state=directory recurse=yes path={{ deploy_to }}/.shared-copy

- name: Get shared path (in rsync case)
  command: echo "{{ deploy_to }}/shared/cached-copy"
  register: shared_path

- name: synchonize application files to remote shared copy
  synchronize: >
    src={{ deploy_from }}
    dest={{ shared_path.stdout }}
    delete=yes

- name: Deploy existing code to servers
  command: cp -pr {{ shared_path.stdout }} {{ deploy.release_path.stdout }}
