---
- name: "Converge: When deploying using Git"
  hosts: all
  become: yes
  become_user: admin

  vars:
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://github.com/ansistrano/git-test.git
    ansistrano_git_branch: master
    ansistrano_deploy_to: "/tmp/git/my-app.com"

  roles:
    - { role: local-ansistrano }

- name: "Converge: And I should be able to do a second deploy"
  hosts: all
  become: yes
  become_user: admin

  vars:
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://github.com/ansistrano/git-test.git
    ansistrano_git_branch: master
    ansistrano_deploy_to: "/tmp/git/my-app.com"

  roles:
    - { role: local-ansistrano }