---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
      config-file: molecule/default/yaml-lint.yml
platforms:
  - name: debian9
    image: debian:9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
