---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
      config-file: molecule/default/yaml-lint.yml
platforms:
  - name: debian
    image: debian:stretch
    # privileged: True
    # cap_add:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # command: "/bin/systemd"
  - name: centos
    image: centos:7
    # privileged: True
    # cap_add:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    # - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
