---
- name: "Coverage: When deploying using download strategy"
  hosts: all
  become: yes
  become_user: admin

  vars:
    ansistrano_deploy_via: "download_unarchive"
    ansistrano_get_url: https://github.com/ansistrano/deploy/archive/1.4.1.zip
    ansistrano_deploy_to: "/tmp/download/my-app.com"

  roles:
    - { role: local-ansistrano }

- name: "Coverage: And I should be able to do a second deploy"
  hosts: all
  become: yes
  become_user: admin

  vars:
    ansistrano_deploy_via: "download_unarchive"
    ansistrano_get_url: https://github.com/ansistrano/deploy/archive/1.4.1.zip
    ansistrano_deploy_to: "/tmp/download/my-app.com"

  roles:
    - { role: local-ansistrano }