---
- name: "Converge: When deploying using download strategy"
  hosts: all
  become: yes
  become_user: admin

  vars_files:
    - "vars/deploy.yml"

  roles:
    - { role: local-ansistrano }

- name: "Converge: And I should be able to do a second deploy"
  hosts: all
  become: yes
  become_user: admin

  vars_files:
    - "vars/deploy.yml"

  roles:
    - { role: local-ansistrano }