---
- include_tasks: download.yml

- name: ANSISTRANO | download_unarchive | Set archived file
  set_fact:
    ansistrano_archived_file: "{{ ansistrano_download_result.dest }}"

- include_tasks: unarchive.yml
