---
- name: ANSISTRANO | Unarchive | Unarchive source
  assert:
    that:
      - (ansistrano_unarchive_owner == "default") == (ansistrano_unarchive_group == "default")
    fail_msg: "must set ansistrano_unarchive_group and ansistrano_unarchive_owner"
  when: >
    ansistrano_unarchive_owner == "default" or
    ansistrano_unarchive_group == "default"

- name: ANSISTRANO | Unarchive | Unarchive source
  unarchive:
    copy: no
    src: "{{ ansistrano_archived_file }}"
    dest: "{{ ansistrano_release_path }}"
    owner: "{{ ansistrano_unarchive_owner if ansistrano_unarchive_owner != 'default' else omit }}"
    group: "{{ ansistrano_unarchive_group if ansistrano_unarchive_group != 'default' else omit }}"
    exclude: "{{ ansistrano_unarchive_exclude }}"
    extra_opts: "{{ ansistrano_unarchive_extra_opts }}"

- name: ANSISTRANO | Unarchive | Delete archived file
  file:
    path: "{{ ansistrano_archived_file }}"
    state: absent
